version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./dev-container/Dockerfile-nginx
        volumes:
            - .:/var/www/symfony/
        ports:
            - 8001:80
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: ./dev-container/Dockerfile-php
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://root:root@mysql:3306/symfony_db
            
        volumes:
            - .:/var/www/symfony/
        networks:
            - symfony
        depends_on:
            - mysql
    mysql:
        image: mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./dev-container/mysql:/var/lib/mysql
        networks:
            - symfony
networks:
    symfony:
