name: Deploy master
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Remove dev files
      run: | 
        rm -rf .docker 
        rm -rf tests 
        rm -f .env
        rm -f .env.test
        rm -f docker-compose.yml
        rm -f phpunit.xml.dist
        rm -f start-docker.ps1
        rm -f stop-docker.ps1
        
    - name: Set Environment Variables
      run: |
        true > .env
        echo "APP_ENV=prod" >> .env
        echo "ENV=PROD" >> .env
        echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
        echo "DATABASE_URL=mysql://admin:5Z$5OWx33YgX@online-training-hub.c65jjxieupzo.eu-central-1.rds.amazonaws.com:3306" >> .env
        
    - name: Install Composer dependencies and warm app cache
      run: |
        composer install --no-dev --optimize-autoloader
        APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear --no-optional-warmers --no-warmup

    - name: Generate deployment package
      run: zip deploy.zip .
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: OnlineTrainingHub
        environment_name: Onlinetraininghub-env
        version_label: 12345
        region: eu-central-1
        deployment_package: deploy.zip
